gems:             [pygments.rb, redcarpet]

#markdown:         kramdown
#highlight:        rouge
#kramdown:
#  input:          GFM
#  syntax_highlighter: rouge
markdown:         redcarpet
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter:      pygments

<<<<<<< HEAD
permalink:        none
version:          2.2

timezone:         Asia/Kuala_Lumpur

=======
#permalink:        /:categories/:title/
version:          2.2

>>>>>>> origin/master
title:            "Heiswayi Nrird on Tech"
tagline:          "Another Software Guy's Blog"
description:      "1+1=3 is always TRUE in my world, a balance between binary and reality."
url:              http://heiswayi.github.io

author:
  name:           "Heiswayi Nrird"
  email:          hnrird@gmail.com
  url:            http://heiswayi.github.io/about.html

github:
  repo:           https://github.com/heiswayi/heiswayi.github.io

twitter:
  username:       HeiswayiNrird

google_analytics: UA-58296043-7

exclude:          [README.md, LICENSE.md]
